---
- name: Personal macOS Environment
  hosts: localhost

  pre_tasks:
    - name: Stop if not macOS
      ansible.builtin.fail:
        msg: This playbook is only for macOS.
      when: ansible_os_family != 'Darwin'

    - name: Update Homebrew
      community.general.homebrew:
        update_homebrew: true

  tasks:
    - name: Homwbrew
      ansible.builtin.import_tasks: tasks/homebrew.yml
    - name: Dotfiles
      ansible.builtin.import_tasks: tasks/dotfiles.yml
    - name: MacOS
      ansible.builtin.import_tasks: tasks/macos.yml
    - name: Neovim
      ansible.builtin.import_tasks: tasks/neovim.yml
    - name: Java
      ansible.builtin.import_tasks: tasks/java.yml
