# yamllint disable rule:line-length
# yaml-language-server: $schema=https://raw.githubusercontent.com/ansible/ansible-lint/main/src/ansiblelint/schemas/ansible.json#/$defs/playbook
# yamllint enable rule:line-length
---
- name: Personal macOS Environment
  hosts: localhost

  pre_tasks:
    - name: Stop if not macOS
      ansible.builtin.fail:
        msg: This playbook is only for macOS.
      when: ansible_os_family != 'Darwin'
      tags: always

    - name: Update Homebrew
      community.general.homebrew:
        update_homebrew: true
      tags: always

    - name: Ensure Common Folders
      ansible.builtin.file:
        state: directory
        path: "{{ item }}"
        mode: "755"
      loop:
        - "{{ common_bin }}"
        - "{{ common_opt }}"
      tags: always

    - name: Create Common Temporary Directory
      ansible.builtin.tempfile:
        state: directory
      register: tempdir
      tags: always

  vars:
    common_bin: "{{ ansible_user_dir }}/bin"
    common_opt: "{{ ansible_user_dir }}/opt"

  tasks:
    - name: Homebrew
      ansible.builtin.import_tasks: tasks/homebrew.yml
      tags:
        - homebrew
        - brew

    - name: Dotfiles
      ansible.builtin.import_tasks: tasks/dotfiles.yml
      tags: dotfiles

    - name: Home Directory
      ansible.builtin.import_tasks: tasks/home.yml
      tags: home

    - name: Yabai
      ansible.builtin.import_tasks: tasks/yabai.yml
      tags:
        - yabai
        - dotfiles

    - name: Skhd
      ansible.builtin.import_tasks: tasks/skhd.yml
      tags:
        - skhd
        - dotfiles

    - name: Node
      ansible.builtin.import_tasks: tasks/node.yml
      tags:
        - node
        - npm

    - name: Java
      ansible.builtin.import_tasks: tasks/java/main.yml
      tags: java

    - name: Go
      ansible.builtin.import_tasks: tasks/go.yml
      tags: go

    - name: Rust
      ansible.builtin.import_tasks: tasks/rust.yml
      tags: rust

    - name: Podman
      ansible.builtin.import_tasks: tasks/podman.yml
      tags: podman

    - name: Terraform
      ansible.builtin.import_tasks: tasks/terraform.yml
      tags: terraform

    - name: Visual Studio Code
      ansible.builtin.import_tasks: tasks/vscode.yml
      tags: vscode

    - name: Neovim
      ansible.builtin.import_tasks: tasks/neovim.yml
      tags: neovim

    - name: Python 3
      ansible.builtin.import_tasks: tasks/python/main.yml
      tags: python
