---
- hosts: localhost

  pre_tasks:
    - name: Stop if not macOS
      ansible.builtin.fail:
        msg: This playbook is only for macOS.
      when: ansible_os_family != 'Darwin'

    - name: Update Homebrew
      community.general.homebrew:
        update_homebrew: true

  tasks:
    - ansible.builtin.import_tasks: tasks/homebrew.yml
    - ansible.builtin.import_tasks: tasks/macos.yml
    - ansible.builtin.import_tasks: tasks/java.yml
