---
- hosts: localhost

  pre_tasks:
    - name: Update Homebrew
      community.general.homebrew:
        update_homebrew: true

  tasks:
    - ansible.builtin.import_tasks: tasks/homebrew.yml
    - ansible.builtin.import_tasks: tasks/macos.yml
    - ansible.builtin.import_tasks: tasks/java.yml
