# yamllint disable rule:line-length
# yaml-language-server: $schema=https://raw.githubusercontent.com/ansible/ansible-lint/main/src/ansiblelint/schemas/ansible.json#/$defs/tasks
# yamllint enable rule:line-length
---
- name: Setup CPython
  vars:
    release_tag: "20231002"
    cpython_archive_name: cpython-{{ cpython_version }}+{{ release_tag }}-aarch64-apple-darwin-pgo+lto-full  # yamllint disable-line rule:line-length
    cpython_sha256: 25fc8cd41e975d18d13bcc8f8beffa096ff8a0b86c4a737e1c6617900092c966  # yamllint disable-line rule:line-length
  block:
    - name: Download and Extract Tarball
      ansible.builtin.import_role:
        name: download_and_extract_tar
      vars:
        download_and_extract_tar_archive_name: "{{ cpython_archive_name }}.tar.zst"  # yamllint disable-line rule:line-length
        download_and_extract_tar_download_url: https://github.com/indygreg/python-build-standalone/releases/download/{{ release_tag }}/{{ cpython_archive_name }}.tar.zst  # yamllint disable-line rule:line-length
        download_and_extract_tar_install_dir: cpython
        download_and_extract_tar_opt_dir: "{{ python_opt_dir }}"
        download_and_extract_tar_pretty_name: CPython 3
        download_and_extract_tar_sha256: "{{ cpython_sha256 }}"
        download_and_extract_tar_tempdir_path: "{{ tempdir.path }}"
        download_and_extract_tar_verify: python/install/bin/python3
