# yamllint disable rule:line-length
# yaml-language-server: $schema=https://raw.githubusercontent.com/ansible/ansible-lint/main/src/ansiblelint/schemas/ansible.json#/$defs/tasks
# yamllint enable rule:line-length
---
- name: Setup virtualenv
  vars:
    target_venv: "{{ python_opt_dir }}/venv"
    python_packages:
      - autopep8
      - awshelp
      - bwenv
      - flake8
      - podman-compose
      - pre-commit
      - tldr
      - tox
      - twine
      - virtualenv
      - yamllint
      - yt-dlp
  block:
    - name: Create virtualenv
      ansible.builtin.import_role:
        name: create_python_venv
      vars:
        create_python_venv_dir: "{{ target_venv }}"
        create_python_venv_packages: "{{ python_packages }}"
        create_python_venv_python_exe: "{{ python_exe }}"
        create_python_venv_tempdir_path: "{{ tempdir.path }}"

    - name: Link Python and Pip Binaries
      ansible.builtin.file:
        state: link
        src: "{{ item }}"
        dest: "{{ ansible_user_dir }}/bin/{{ item | basename }}"
      with_fileglob:
        - "{{ target_venv }}/bin/pip"
        - "{{ target_venv }}/bin/pip3"
        - "{{ target_venv }}/bin/pip3.*"
        - "{{ target_venv }}/bin/python"
        - "{{ target_venv }}/bin/python3"
        - "{{ target_venv }}/bin/python3.*"

    - name: Link Python Package Binaries
      ansible.builtin.file:
        state: link
        src: "{{ target_venv }}/bin/{{ item }}"
        dest: "{{ ansible_user_dir }}/bin/{{ item }}"
      loop: "{{ python_packages }}"
