# yamllint disable rule:line-length
# yaml-language-server: $schema=https://raw.githubusercontent.com/ansible/ansible-lint/main/src/ansiblelint/schemas/ansible.json#/$defs/tasks
# yamllint enable rule:line-length
---
- name: Setup PyPI Ansible
  vars:
    target_venv: "{{ ansible_user_dir }}/opt/ansible-venv"
    python_packages:
      - ansible
      - ansible-lint
  block:
    - name: Download virtualenv
      ansible.builtin.get_url:
        url: https://bootstrap.pypa.io/virtualenv.pyz
        dest: /tmp/virtualenv.pyz
        mode: "755"

    # virutalenv.pyz path cannot contain symlinks
    # In macOS, /tmp is a symlink to /private/tmp
    # See https://github.com/pypa/virtualenv/issues/1949
    - name: Create Ansible virtualenv
      ansible.builtin.command:
        cmd: >
          "{{ ansible_python.executable }}"
          /private/tmp/virtualenv.pyz
          -p /usr/bin/python3
          "{{ target_venv }}"
        creates: "{{ target_venv }}/bin/python"

    - name: Install Ansible Packages
      ansible.builtin.pip:
        virtualenv: "{{ target_venv }}"
        state: latest  # noqa package-latest
        name: "{{ python_packages }}"

    - name: Link Ansible Package Binaries
      ansible.builtin.file:
        state: link
        src: "{{ item }}"
        dest: "{{ ansible_user_dir }}/bin/{{ item | basename }}"
      with_fileglob:
        - "{{ target_venv }}/bin/ansible*"

- name: Remove Homebrew Ansible
  community.general.homebrew:
    state: absent
    name: ansible
