---
- name: Update All Homebrew Packages
  community.general.homebrew:
    upgrade_all: true

- name: Install Homebrew Packages
  community.general.homebrew:
    state: present
    name:
      - bat
      - bitwarden-cli
      - clang-format
      - fzf
      - git
      - jq
      - parallel
      - tmux
      - tree
      - watch
      - wget
      - zsh

      # Use GNU versions over BSD
      - findutils
      - gnu-sed
      - gnu-tar

- name: Setup Homebrew Taps
  community.general.homebrew_tap:
    state: present
    name:
      - homebrew/cask-fonts

- name: Install Homebrew Cask Packages
  community.general.homebrew_cask:
    state: present
    name:
      - alacritty
      - bitwarden
      - firefox
      - font-hack-nerd-font
      - gimp
      - google-chrome
      - inkscape
      - iterm2
      - visual-studio-code
      - vlc

- name: Homebrew Autoremove
  ansible.builtin.command: brew autoremove
  register: autoremove
  changed_when: autoremove.stdout != ""

- name: Homebrew Cleanup
  ansible.builtin.command: brew cleanup
  register: cleanup
  changed_when: cleanup.stdout != ""
