# yamllint disable rule:line-length
# yaml-language-server: $schema=https://raw.githubusercontent.com/ansible/ansible-lint/main/src/ansiblelint/schemas/ansible.json#/$defs/tasks
# yamllint enable rule:line-length
---
- name: Update All Homebrew Packages
  community.general.homebrew:
    upgrade_all: true

- name: Install Homebrew Packages
  community.general.homebrew:
    state: present
    name:
      - bitwarden-cli
      - fzf
      - git
      - jq
      - parallel
      - tree
      - watch
      - wget
      - zsh

      # Use GNU versions over BSD
      - findutils
      - gnu-sed
      - gnu-tar

- name: Setup Homebrew Taps
  community.general.homebrew_tap:
    state: present
    name:
      - homebrew/cask-fonts

- name: Install Homebrew Cask Packages
  community.general.homebrew_cask:
    state: present
    name:
      - 1password
      - 1password-cli
      - alacritty
      - bitwarden
      - calibre
      - firefox
      - font-jetbrains-mono-nerd-font
      - gimp
      - google-chrome
      - inkscape
      - iterm2
      - the-unarchiver
      - visual-studio-code
      - vlc

- name: Homebrew Autoremove
  ansible.builtin.command: brew autoremove
  register: autoremove
  changed_when: autoremove.stdout != ""

- name: Homebrew Cleanup
  ansible.builtin.command: brew cleanup
  register: cleanup
  changed_when: cleanup.stdout != ""
