---
- name: Install Neovim and Dependencies
  community.general.homebrew:
    state: present
    name:
      - neovim
      - ripgrep
      - stylua

- name: Install Neovim Plugins
  ansible.builtin.command: nvim --headless '+Lazy! restore' +qa
  register: result
  changed_when: result.stderr != ""
