---
- name: Install Neovim Dependencies
  community.general.homebrew:
    state: present
    name:
      - lua-language-server

      # Build deps
      - ccache
      - cmake
      - curl
      - gettext
      - ninja

- name: Ensure opt folder
  ansible.builtin.file:
    state: directory
    path: "{{ ansible_user_dir }}/opt/neovim"
    mode: "755"

- name: Clone Neovim Repo
  ansible.builtin.git:
    accept_newhostkey: true
    depth: 1
    dest: "{{ ansible_user_dir }}/opt/neovim/repo"
    repo: git@github.com:neovim/neovim
    version: stable
  register: clone

- name: Remove Old Neovim Build
  when: clone.before != clone.after
  ansible.builtin.file:
    state: absent
    path: "{{ ansible_user_dir }}/opt/neovim/repo/build"

- name: Build & Install Neovim
  when: clone.before != clone.after
  community.general.make:
    target: install
    chdir: "{{ ansible_user_dir }}/opt/neovim/repo"
    params:
      CMAKE_BUILD_TYPE: Release
      CMAKE_INSTALL_PREFIX: "{{ ansible_user_dir }}/opt/neovim/build"

- name: Link Neovim
  ansible.builtin.file:
    state: link
    src: "{{ ansible_user_dir }}/opt/neovim/build/bin/nvim"
    dest: "{{ ansible_user_dir }}/bin/nvim"

- name: Install Neovim Plugins
  ansible.builtin.command: nvim --headless '+Lazy! restore' +qa
  register: result
  changed_when: result.stderr != ""

- name: Remove Homebrew Neovim
  community.general.homebrew:
    state: absent
    name: neovim
