# yamllint disable rule:line-length
# yaml-language-server: $schema=https://raw.githubusercontent.com/ansible/ansible-lint/main/src/ansiblelint/schemas/ansible.json#/$defs/tasks
# yamllint enable rule:line-length
---
- name: Install Neovim Dependencies
  community.general.homebrew:
    state: present
    name:
      - clang-format
      - lua-language-server

      # Build deps
      - ccache
      - cmake
      - curl
      - gettext
      - ninja

- name: Clone Neovim Repository
  ansible.builtin.git:
    accept_newhostkey: true
    depth: 1
    dest: "{{ common_opt }}/neovim/repo"
    repo: git@github.com:neovim/neovim
    version: stable
  register: clone

- name: Build Neovim
  when: clone.before != clone.after
  block:
    - name: Clean Neovim Repository  # noqa: command-instead-of-module
      ansible.builtin.command: git clean -ffxd
      register: result
      changed_when: result.stdout != ""

    - name: Build & Install Neovim
      community.general.make:
        target: install
        chdir: "{{ common_opt }}/neovim/repo"
        params:
          CMAKE_BUILD_TYPE: Release
          CMAKE_INSTALL_PREFIX: "{{ common_opt }}/neovim/build"

- name: Link Neovim
  ansible.builtin.file:
    state: link
    src: "{{ common_opt }}/neovim/build/bin/nvim"
    dest: "{{ common_bin }}/nvim"

- name: Install Neovim Plugins
  ansible.builtin.command: nvim --headless '+Lazy! restore' +qa
  register: result
  changed_when: result.stderr != ""

- name: Remove Homebrew Neovim
  community.general.homebrew:
    state: absent
    name: neovim
