# yamllint disable rule:line-length
# yaml-language-server: $schema=https://raw.githubusercontent.com/ansible/ansible-lint/main/src/ansiblelint/schemas/ansible.json#/$defs/tasks
# yamllint enable rule:line-length
---
- name: Install Podman
  community.general.homebrew:
    state: present
    name:
      - docker
      - docker-compose
      - podman

- name: Create Podman Machine
  ansible.builtin.command: podman machine init
  register: machine_init
  changed_when: machine_init.rc == 0
  failed_when:
    - machine_init.rc != 0
    - machine_init.rc != 125  # machine already exists

- name: Install Podman System Helper for docker.sock
  ansible.builtin.command: podman-mac-helper install
  become: true
  register: system_helper
  changed_when: "'helper is already installed' not in system_helper.stderr"
