# yamllint disable rule:line-length
# yaml-language-server: $schema=https://raw.githubusercontent.com/ansible/ansible-lint/main/src/ansiblelint/schemas/ansible.json#/$defs/tasks
# yamllint enable rule:line-length
---
- name: Install Terraform
  when: ansible_machine == 'arm64'
  vars:
    terraform_version: 1.6.0
    terraform_sha256: aaf3f6639c9fd3864059955a36ccdadd7b54bab681fbe760525548a53cc0c7ec  # yamllint disable-line rule:line-length
    terraform_archive_name: "terraform_{{ terraform_version }}_darwin_arm64"
  block:
    - name: Download Terraform zip
      ansible.builtin.get_url:
        url: "https://releases.hashicorp.com/terraform/{{ terraform_version }}/{{ terraform_archive_name }}.zip"  # yamllint disable-line rule:line-length
        checksum: "sha256:{{ terraform_sha256 }}"
        dest: "/tmp/{{ terraform_archive_name }}.zip"
        mode: "755"

    - name: Ensure opt folder
      ansible.builtin.file:
        state: directory
        path: "{{ ansible_user_dir }}/opt/{{ terraform_archive_name }}"
        mode: "755"

    - name: Unzip Terraform zip
      ansible.builtin.unarchive:
        src: "/tmp/{{ terraform_archive_name }}.zip"
        dest: "{{ ansible_user_dir }}/opt/{{ terraform_archive_name }}"
        remote_src: true
        creates: >
          "{{ ansible_user_dir }}/opt/{{ terraform_archive_name }}/terraform"
        mode: "755"

    - name: Link Terraform Binary
      ansible.builtin.file:
        state: link
        src: "{{ ansible_user_dir }}/opt/{{ terraform_archive_name }}/terraform"
        dest: "{{ ansible_user_dir }}/bin/terraform"

    - name: Find Old Terraform
      ansible.builtin.find:
        paths: "{{ ansible_user_dir }}/opt"
        pattern: "terraform_*"
        file_type: directory
      register: old_terraform

    - name: Purge Old Terraform
      ansible.builtin.file:
        state: absent
        path: "{{ item.path }}"
      vars:
        paths_to_keep:
          - "{{ ansible_user_dir }}/opt/{{ terraform_archive_name }}"
      when: item.path not in paths_to_keep
      loop: "{{ old_terraform.files }}"

- name: Install Terraform Language Server
  community.general.homebrew:
    state: present
    name: terraform-ls
