# yamllint disable rule:line-length
# yaml-language-server: $schema=https://raw.githubusercontent.com/ansible/ansible-lint/main/src/ansiblelint/schemas/ansible.json#/$defs/tasks
# yamllint enable rule:line-length
---
- name: Install Terraform
  when: ansible_machine == 'arm64'
  vars:
    terraform_version: 1.8.0
    terraform_sha256: abfb06eb80f1acd19ab8a01f6d24a4a5f99ba9b628c3b00a3b0c898709eea3b3  # yamllint disable-line rule:line-length
    terraform_archive_name: terraform_{{ terraform_version }}_darwin_arm64
    terraform_opt_dir: "{{ common_opt }}/terraform-{{ terraform_version }}"
  block:
    - name: Download and Extract Tarball
      ansible.builtin.import_role:
        name: download_and_extract_tar
      vars:
        download_and_extract_tar_archive_name: "{{ terraform_archive_name }}.zip"  # yamllint disable-line rule:line-length
        download_and_extract_tar_download_url: https://releases.hashicorp.com/terraform/{{ terraform_version }}/{{ terraform_archive_name }}.zip  # yamllint disable-line rule:line-length
        download_and_extract_tar_install_dir: "{{ terraform_archive_name }}"
        download_and_extract_tar_opt_dir: "{{ terraform_opt_dir }}"
        download_and_extract_tar_pretty_name: Terraform
        download_and_extract_tar_sha256: "{{ terraform_sha256 }}"
        download_and_extract_tar_tempdir_path: "{{ tempdir.path }}"
        download_and_extract_tar_verify: terraform

    - name: Link Terraform Binary
      ansible.builtin.file:
        state: link
        src: "{{ terraform_opt_dir }}/{{ terraform_archive_name }}/terraform"
        dest: "{{ common_bin }}/terraform"

    - name: Purge Old Terraform
      ansible.builtin.import_role:
        name: purge_old_install
      vars:
        purge_old_install_new_install: "{{ terraform_opt_dir }}"
        purge_old_install_pattern: terraform-*
        purge_old_install_pretty_name: Terraform
