# yamllint disable rule:line-length
# yaml-language-server: $schema=https://raw.githubusercontent.com/ansible/ansible-lint/main/src/ansiblelint/schemas/ansible.json#/$defs/tasks
# yamllint enable rule:line-length
---
- name: Install Visual Studio Code
  community.general.homebrew_cask:
    state: present
    name:
      - visual-studio-code

- name: Install Visual Studio Code Extensions
  ansible.builtin.command: code --install-extension "{{ item }}"
  loop:
    - EditorConfig.EditorConfig
    - PKief.material-icon-theme
    - aaron-bond.better-comments
    - hediet.vscode-drawio
    - mikestead.dotenv
    - streetsidesoftware.code-spell-checker
    - teabyii.ayu
    - zhuangtongfa.material-theme
  register: result
  changed_when: "'successfully installed' in result.stdout"

- name: Update Visual Studio Code Extensions
  ansible.builtin.command: code --update-extensions
  register: result
  changed_when: "'No extension to update' in result.stdout"
