# yamllint disable rule:line-length
# yaml-language-server: $schema=https://raw.githubusercontent.com/ansible/ansible-lint/main/src/ansiblelint/schemas/role-arg-spec.json
# yamllint enable rule:line-length
---
argument_specs:
  main:
    short_description: Find and purge old installs
    options:
      purge_old_install_new_install:
        type: str
        required: true
      purge_old_install_pattern:
        type: str
        required: true
      purge_old_install_pretty_name:
        type: str
        required: true
