# yamllint disable rule:line-length
# yaml-language-server: $schema=https://raw.githubusercontent.com/ansible/ansible-lint/main/src/ansiblelint/schemas/ansible.json#/$defs/tasks
# yamllint enable rule:line-length
---
- name: Download Lombok JAR
  vars:
    # https://projectlombok.org/download
    lombok_version: 1.18.36
    lombok_archive_name: lombok-{{ lombok_version }}
    lombok_sha256: 73b6b05b6a2d365b700bab08d30f94de9d336490bc0acce5b6181fef48cbf18e  # yamllint disable-line rule:line-length
  ansible.builtin.get_url:
    url: https://projectlombok.org/downloads/{{ lombok_archive_name }}.jar
    checksum: sha256:{{ lombok_sha256 }}
    dest: "{{ java_opt_dir }}/lombok.jar"
    mode: "755"
