# yamllint disable rule:line-length
# yaml-language-server: $schema=https://raw.githubusercontent.com/ansible/ansible-lint/main/src/ansiblelint/schemas/ansible.json#/$defs/tasks
# yamllint enable rule:line-length
---
- name: Download Lombok JAR
  vars:
    # https://projectlombok.org/download
    lombok_version: 1.18.38
    lombok_archive_name: lombok-{{ lombok_version }}
    lombok_sha256: 1e1e427c36ff63c44fd30ef292d9e773ea3154460ab6265d3fed7e6f5bc50fb9  # yamllint disable-line rule:line-length
  ansible.builtin.get_url:
    url: https://projectlombok.org/downloads/{{ lombok_archive_name }}.jar
    checksum: sha256:{{ lombok_sha256 }}
    dest: "{{ java_opt_dir }}/lombok.jar"
    mode: "755"
