# yamllint disable rule:line-length
# yaml-language-server: $schema=https://raw.githubusercontent.com/ansible/ansible-lint/main/src/ansiblelint/schemas/ansible.json#/$defs/tasks
# yamllint enable rule:line-length
---
- name: Download Lombok JAR
  vars:
    # https://projectlombok.org/download
    lombok_version: 1.18.30
    lombok_archive_name: lombok-{{ lombok_version }}
    lombok_sha256: d7ee122eee1eaeeb45182a89ff36fc2dd086858d1b2f54b615c6fef7ba1d6012  # yamllint disable-line rule:line-length
  ansible.builtin.get_url:
    url: https://projectlombok.org/downloads/{{ lombok_archive_name }}.jar
    checksum: sha256:{{ lombok_sha256 }}
    dest: "{{ java_opt_dir }}/lombok.jar"
    mode: "755"
